### PR TITLE
add Chinese Mandarin translation

### PR DESCRIPTION
**Pull request by livc**

### CODE REVIEW

**Comment by ro31337** [comment]
Thanks for translation! I need to make some work to add the translation to the bot (Telegram limitation - 6 language buttons). When it's done (it's number 1 priority), I'll merge your PR.

**Comment by unohuang** [comment]
Not a good translation though.

**Comment by livc** [comment]
@unojazz I think you can help review the translation, thanks.

**Comment by unohuang** [comment]
I'll do Traditional Chinese part, thx.

**Comment by ro31337** [comment]
Thanks for translation @livc , merging. Will deploy in minutes. Bot already supports Mandarin Chinese. @unojazz I appreciate if you can review Mandarin translation for this repo (if it is required), and it would be better guys if you can collaborate together.

**Pull request merged**
