### PR TITLE
Creating index-sv.html translation of www site

### PR DESCRIPTION
**Pull request by mattiasaxell**
One person has translated and added some changes in order to adapt the text to Swedish language and context. I have reviewed it afterwards.

### CODE REVIEW

**Comment by mattiasaxell** [comment]
Can you add this to LibreTaxi.org site? @ro31337

**Comment by ro31337** [comment]
So cool, thanks! I'll come back home, update some links and merge it!

**Comment by ro31337** [comment]
@mattiasaxell merged with master, thank you. Updating links. Is there any chance you can add a file to https://github.com/ro31337/libretaxi/tree/master/locales and translate the app itself?

Instructions can be found here:

https://github.com/ro31337/libretaxi/blob/master/doc/TRANSLATE.md

**Comment by mattiasaxell** [comment]
@ro31337 Great! Thanks. Yes, making a PR soon. www site and app has been customised for Swedish context.

**Pull request merged**
